clear
load('PositionInfo.mat')
load('ResultNuffGlass.mat')
std_log=std(real(log(Data)),[],2);
std=std((Data),[],2);
Avg_log=mean(real(log(Data)),2);
Avg=mean((Data),2);
figure(1)
errorbar(R_Set*0.23,Avg,std)
hold on
figure(2)
errorbar(R_Set*0.23,Avg_log,std_log)
hold on
clear
load('PositionInfo.mat')
load('ResultNuff3kpa.mat')
std_log=std(real(log(Data)),[],2);
std=std((Data),[],2);
Avg_log=mean(real(log(Data)),2);
Avg=mean((Data),2);
figure(1)
errorbar(R_Set*0.23,Avg,std)
figure(2)
errorbar(R_Set*0.23,Avg_log,std_log)
clear
load('PositionInfo.mat')
load('ResultMDCKGlass.mat')
std_log=std(real(log(Data)),[],2);
std=std((Data),[],2);
Avg_log=mean(real(log(Data)),2);
Avg=mean((Data),2);
figure(1)
errorbar(R_Set*0.23,Avg,std)
figure(2)
errorbar(R_Set*0.23,Avg_log,std_log)
clear
load('PositionInfo.mat')
load('Result3T3Glass.mat')
std_log=std(real(log(Data)),[],2);
std=std((Data),[],2);
Avg_log=mean(real(log(Data)),2);
Avg=mean((Data),2);
figure(1)
errorbar(R_Set*0.23,Avg,std)
figure(2)
errorbar(R_Set*0.23,Avg_log,std_log)

figure(1)
legend('NuffGlass','Nuff3kpa','MDCKGlass','3T3Glass')
figure(2)
legend('NuffGlass','Nuff3kpa','MDCKGlass','3T3Glass')